### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by basememara** [kean/NukeUI#1]
This is really great, thx for this!

Can you tag this and lock the Nuke version in the package manager to `10.0.0`? Because I use other dependencies, like GetStream, that also uses Nuke as a dependency so the versions need to line up.

**Comment by kean** [comment]
Hey, I'm glad you like it, but it's a bit early. It's still work in progress. I'm planning to push the first beta version soon.

**Comment by kean** [comment]
Yeah, I can target the version. Thanks for the MR!

**Comment by basememara** [comment]
Awesome thx! I love the API.. it's so elegant! Light years ahead of `FetchImage` in such a short time.
