### ISSUE TITLE
Support for AsyncImage wrapper or view modifier

### ISSUE THREAD

**Issue by Cyclic** [kean/NukeUI#10]
It would be nice if this package implemented the same features, such as the caching and gif support, using the new, OOB, AsyncImage in SwiftUI. Perhaps using phases?

**Comment by kean** [comment]
Could you please elaborate? GIF support, caching is what AsyncImage *doesn't* support and NukeUI does.

**Comment by Cyclic** [comment]
In other words, rather than a new type, if you can create a view modifier for the new AsyncImage, which enables caching, and gif animations, and uses the new phases of AsyncImage to do it, it would be nice. If you cannot use a view modifier, then I was thinking you might just inherit from AsyncImage. Would animated gifs work with the canvas feature. I only bring this up as an additional solution since the work for async image is already implemented.

**Comment by kean** [comment]
Hey, I think trying to add something on top of AsyncImage is not possible. NukeUI provides a custom component that does what AsyncImage does and much more.
