### ISSUE TITLE
LazyImage doesn't work with drawHierarchy

### ISSUE THREAD

**Issue by Bersaelor** [kean/NukeUI#12]
In our app we sometimes need to make static images of our UI and it seems the SwiftUI method [`drawHierarchy`](https://developer.apple.com/documentation/uikit/uiview/1622589-drawhierarchy) seems to not show anything in places of a `LazyImage`, .e.g:

```
        let controller = UIHostingController(rootView: self)
        let renderer = UIGraphicsImageRenderer(size: controller.view.size)

        let image = renderer.image { _ in
            view?.drawHierarchy(in: controller.view.bounds, afterScreenUpdates: true)
        }
```

**Comment by kean** [comment]
Hi @Bersaelor. Thanks for the report, but I'm not entirely sure how these systems interact. If you find a solution, I would appreciate if you could share it.

**Comment by kean** [comment]
Turns out it's a known problem in SwiftUI and the new `ImageRenderer` type addressed it.
