### ISSUE TITLE
[Question] How to use NukeUI to display local images from Photo Gallery?

### ISSUE THREAD

**Issue by antranapp** [kean/NukeUI#15]
Thank you for this great library

I'm using Kingfisher and implement its [ImageDataProvider](https://github.com/onevcat/Kingfisher/blob/master/Sources/General/ImageSource/ImageDataProvider.swift) to fetch data from  images in Photos Gallery.

Is it possible to do that with `NukeUI` as well?

**Comment by kean** [comment]
`ImageRequest` can be [initializer](https://kean.blog/nuke/guides/customizing-requests#sources) with a `Data` publisher.

```swift
let request = ImageRequest(
    id: "image-01",
    data: Just(data),
    processors: [ImageProcessors.Resize(width: 44)]
)
```

You can use an asset identifier as an image id and wrap a `PHImageManager` call to fetch image data into a Combine publisher.

But in general, it's best to use `PHImageManager` directly wherever possible. If you want to use [requestImage(...)](https://developer.apple.com/documentation/photokit/phimagemanager/1616964-requestimage) API, you can use FetchImage to [manage the download](https://kean.blog/nuke/guides/swiftui#combine). It's built on top of Combine as well.

`LazyImage` and `LazyImageView` don't yet support custom Combine publisher, but it should be easy to add.
