### ISSUE TITLE
Can't use NukeUI in macOS Catalyst App

### ISSUE THREAD

**Issue by Mackarous** [kean/NukeUI#16]
I am building an app that has an internal private Swift Package where I do most of my work shared across multiple targets

One of those targets is a macOS Catalyst app

My SPM product contains `NukeUI` as one of the target dependencies, however there are build errors since macOS Catalyst seems to build as an iOS app under a macOS environment? I'm new to it so I am not sure what's happening, but this is the list of errors I get, which is odd since they are inside a `#if os(iOS) || os(tvOS)`

Just to note, building the target using any iOS device works, but when I change the scheme to macOS, it fails

<img width="457" alt="Screen Shot 2021-07-30 at 02 09 53" src="https://user-images.githubusercontent.com/1043281/127608700-2d9bea69-9d69-4080-b752-59d29918bede.png">

**Comment by waltflanagan** [comment]
I'm seeing this too building a vanilla mac App,  Nuke and NukeUI both declare macOS support but `Gifu` doesn't support macOS.

**Comment by kean** [comment]
Fixed in [0.6.8](https://github.com/kean/NukeUI/releases/tag/0.6.8). I wasn't sure how to make animated images work on Catalyst, but at least it now compiles.

**Comment by Mackarous** [comment]
Awesome! Thanks @kean
