### ISSUE TITLE
Watch OS error

### ISSUE THREAD

**Issue by haifengkao** [kean/NukeUI#18]
I am trying to publish `NukeUI` to cocoapod, but I encountered the following error.
```
NukeUI/NukeUI/Classes/LazyImage.swift:254:23: error: type 'ImageDecoders' has no member 'Video'
```

It seems that `Video` is not defined for WatchOS.

Cocoapod ensure all published pods can be compiled, but Swift Package doesn't have such feature.
Actually, SPM is inferior to Cocoapod in all aspects.
I really don't understand why people switch to SPM.

**Comment by kean** [comment]
The podspec is now available too.
