### ISSUE TITLE
Question: How can we stop animations when image is displayed.

### ISSUE THREAD

**Issue by scottandrew** [kean/NukeUI#19]
I am using LazyImage in a VStack and I have a question. When a gif is loaded I only want to display its first frame. But how can I prevent the animation using LazyImage? Its my last piece of a puzzle..

**Comment by kean** [comment]
This disabled rendering completely.

```swift
LazyImage(source: nil)
    .onCreated {
        $0.isAnimatedImageRenderingEnabled = false
 }
```

But ideally I would replace the default image decoder to make sure it creates a GIF preview but doesn't attach image data (required for animated image playback) to the `ImageContainer` instances it creates.

**Comment by scottandrew** [comment]
This is perfect. I think we want the data because we want to display the animations if they click it the image to view it. Thank you.
