### ISSUE TITLE
Add support for iOS 13

### ISSUE THREAD

**Issue by stefanosheaDeputy** [kean/NukeUI#22]
In release 0.5.0, the minimum supported version was bumped to iOS 14.0 "_temporarily_". Is this still temporary and will iOS 13 be supported again soon? Our app will likely be supporting iOS 13 for another few months.

**Comment by kean** [comment]
The framework is available on iOS 12 and higher. `LazyImage` is iOS 14-only because it relies on `@StateObject` and `onChange(of:)`. I'm not sure it it's even possible to replace them and I don't think it's worth investing time into it – SwiftUI on iOS 13 is pretty bad.
