### ISSUE TITLE
LazyImage in List elements

### ISSUE THREAD

**Issue by andrei4002** [kean/NukeUI#26]
I'm trying to use `LazyImage` inside `List`, by giving it an aspect ratio like this:

```
struct ContentView: View {
    var data = (1...50).map { $0 }
    var ratios: [CGFloat] = [16/9, 21/3, 1]
    
    var aspectRatio: CGFloat {
        ratios.randomElement()!
    }
    
    var body: some View {
        NavigationView {
            List {
                ForEach(data, id: \.self) { model in
                    LazyImage(source: "https://picsum.photos/300/300")
                        .aspectRatio(aspectRatio, contentMode: .fill)
                        .padding(.horizontal)
                        .padding(.bottom)
                }
                .listRowSeparator(.hidden)
                .listRowBackground(Color.clear)
                .listRowInsets(.init(top: 0, leading: 0, bottom: 0, trailing: 0))
            }
            .listStyle(.plain)
            
        }
    }
}
```

The problem is that the elements get overlapped when you scroll, like this:

![image](https://user-images.githubusercontent.com/475334/142211333-d4444082-816c-49ab-99f4-fae3da073157.png)

This doesn't reproduce if i use `ScrollView`, only with `List`

**Comment by kean** [comment]
The view doesn't know the size of the image before it downloads it. Thus, you must specify the view size before loading the image. By default, the image will resize preserving the aspect ratio to fill the available space. You can change this behavior by passing a different resizing mode.

```swift
LazyImage(source: "https://example.com/image.jpeg", resizingMode: .center)
    .frame(height: 300)
```

**Comment by andrei4002** [comment]
i'm not sure if we're talking about the same thing here. In my case i have a `List` of `LazyImage`s that are being set with an external aspect ratio, on the view itself - i believe this should force the image view container to have a particular height based on the requested aspect ratio, regardless of the final image result's size/aspect ratio (at least this is what applying aspect ratio to another type of view like `Color` or `Rectangle` etc does)

My issue in particular here is that by using `List` instead of `ScrollView`, not sure which of the following happens (or both?) : either the image "spills" outside its container, or the height of the image container is not set based on the aspect ratio modifier after it

**Comment by StarPlayrX** [comment]
Try using LazyVGrid or LazyHGrid instead and put it inside a scroll view.

Also use LazyHstack or LazyVStack.
