### ISSUE TITLE
Image goes black when using SwiftUI contextMenu

### ISSUE THREAD

**Issue by jtressle** [kean/NukeUI#29]
I'm using a LazyImage in a LazyVGrid.  The LazyImage is called:
`LazyImage(source: url, resizingMode: .aspectFill)`

When I long press the image, the image goes blank when long pressed to trigger the contextMenu.  I replaced the LazyImage with the following ImageView and everything works fine.  

My app is iOS 14.3 and above, and my device has iOS 15.0.2 installed.  

```
struct ImageView: View {
	let url: URL?
	
	@StateObject private var image = FetchImage()
	
	var body: some View {
		ZStack {
			Rectangle().fill(Color.primary)
			image.view?
				.resizable()
				.aspectRatio(contentMode: .fill)
				.clipped()
		}
		.onAppear {
			if let url = url {
				image.load(url)
			}
		}
		.onChange(of: url) { image.load($0) }
		.onDisappear(perform: image.reset)
	}
}
```

Is this a known issue, or is there something I need to adjust?  

Thanks

**Comment by kean** [comment]
Can you please re-test with [0.8.0](https://github.com/kean/NukeUI/releases/tag/0.8.0)

**Comment by kylebrowning** [comment]
This is still happening
