### ISSUE TITLE
Issue loading gif

### ISSUE THREAD

**Issue by IssaMansour** [kean/NukeUI#34]
Hello,

When trying to load images this way:
`LazyImage(source: $0) { state in
    if let image = state.image {
        image // Displays the loaded image
    } else if state.error != nil {
        Color.red // Indicates an error
    } else {
        Color.blue // Acts as a placeholder
    }
}`
gif are not animated.
But it works with the simple call: ` LazyImage(source: imageUrl, resizingMode: .aspectFill)`.

Any idea?

**Comment by kean** [comment]
Fixed in [0.8.0](https://github.com/kean/NukeUI/releases/tag/0.8.0)
