### ISSUE TITLE
Crash IOS 14.4

### ISSUE THREAD

**Issue by leogiroux** [kean/NukeUI#35]
I was just scrolling a view with images.

Fatal error: Attempted to read an unowned reference but the object was already deallocated2022-01-26 15:27:24.629614+0100 Sybel[28238:2059206] 
Fatal error: Attempted to read an unowned reference but the object was already deallocated
Fatal error: Attempted to read an unowned reference but the object was already deallocated
CoreSimulator 776.4 - Device: iPhone X (ECF98794-9275-4AC5-854C-235CA8CD9FAF) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone X
<img width="947" alt="Capture d’écran 2022-01-26 à 15 29 50" src="https://user-images.githubusercontent.com/12122348/151181741-b4b765b8-c8ae-45f9-a4a1-a97defd97c4b.png">

**Comment by kean** [comment]
Fixed in [0.8.0](https://github.com/kean/NukeUI/releases/tag/0.8.0)

**Comment by kean** [comment]
Make sure to also update to Nuke [10.7.1](https://github.com/kean/Nuke/releases/tag/10.7.1)
