### ISSUE TITLE
Failed to decode image

### ISSUE THREAD

**Issue by nick70007** [kean/NukeUI#38]
In my SwiftUI App i am trying to load post requested image by passing imagerequest to source initializer but if fails

trying to load image from this link:
 [https://ipfs.infura.io:5001/api/v0/block/cat?arg=QmcrJRMrFnGGHtC4bwkDYsnqaG9fmGSV6qHATa9h6j3jxi](url)

let url = try! ImageRequest(urlRequest: URLRequest(url: obj.displayCoverLink, method: .post)).asImageRequest()
                
                LazyImage(source: url) { state in
                    if let img = state.image {
                        img
                            .aspectRatio(contentMode: .fill)
                    } else {
                        Image("placeholder")
                            .resizable()
                            .frame(width: 25, height: 25, alignment: .center)
                            .scaledToFit()
                    }
                }
                .onSuccess({ response in
                    print(response)
                })
                .onFailure({ error in
                    print(error)
                })
                .frame(width: 80, height: 100)
                .transition(.fade(duration: 0.5))
                .cornerRadius(10)
                .shadow(color: Color.black.opacity(0.25), radius: 4, x: 0, y: 4)

**Comment by kean** [comment]
Hi, it also fails to load in a browser. It looks an issue with an original image.
