### ISSUE TITLE
Unable to change default view/color while image is loading

### ISSUE THREAD

**Issue by dannyhertz** [kean/NukeUI#39]
I might be wrong but I do not see any way to alter the default view displayed while an image is loading. I am using LazyImage to load a somewhat transparent gif and it shows a gray square while its loading and I'd love to use a clear color or hide the view entirely until it's ready to be shown. Is this possible today or something you would accept a PR for? 

Thanks!

**Comment by NathHorrigan** [comment]
@dannyhertz - How did you fix this?
