### ISSUE TITLE
MP4 loop stops when app is put in background 

### ISSUE THREAD

**Issue by AndyMeagher** [kean/NukeUI#44]
The Video playback works perfectly however the video stops when the app is put in the background. 
I would expect the Video playback to resume when I bring the app back in the foreground but it does not. 

Is this expected and is there a way to get the video to resume?

**Comment by MinhPhuPham** [comment]
Have any update for this ticket?

**Comment by kean** [comment]
> Is this expected and is there a way to get the video to resume?

This is not expected and PRs are very welcome.
