### ISSUE TITLE
Dependency on Gifu

### ISSUE THREAD

**Issue by GZaccaroni** [kean/NukeUI#47]
I'd like to use NukeUI on my app but I don't want Gifu, I think it would be better to have two targets (one without gif support), in order to reduce unused dependencies.

p.s. Thank you for this great library !

**Comment by kean** [comment]
Hi, I understand the desire to reduce transient dependencies. Starting from Nuke 11, which is currently [in beta](https://github.com/kean/Nuke/releases/tag/11.0.0-beta.1), NukeUI module is part of the main repo. It also no longer publicly exposes Gifu dependency or its public APIs.
