### ISSUE TITLE
Unable to add package

### ISSUE THREAD

**Issue by eliottrobson** [kean/NukeUI#48]
Hi,

I'm trying to add the package to my Xcode project but getting the error "Failed to resolve dependencies".

<img width="646" alt="Screenshot 2022-06-28 at 20 41 20" src="https://user-images.githubusercontent.com/2973685/176271289-27ad7346-cb8f-4b1c-90fd-3504328a68db.png">

Clicking "Add Anyway" adds the package, but it fails to resolve and causes the project to fail to build (copying components from another project that already use this).

Is there something special I need to do?

Thanks

**Comment by eliottrobson** [comment]
Looks like I just needed to ensure my version of Nuke was 10.x, is it possible to add a table to this project readme which shows which versions are compatible?

**Comment by kean** [comment]
Great!

You can see which version is required in the Package.swift file https://github.com/kean/NukeUI/blob/main/Package.swift.

Also, with [Nuke 11](https://github.com/kean/Nuke/pull/547), this package is moving to the main repo, so it'll be easier to install and update. All packages will be released together with the same version number.
