### ISSUE TITLE
Consider an iOS 13 compatible LazyImage

### ISSUE THREAD

**Issue by kylebrowning** [kean/NukeUI#8]
Essentially we can't upgrade to Nuke 10 until we can remove `FetchImage`.

You can mark this as closed if its something you just don't want to do but I imagine there will be holdouts until people can drop support for iOS 13.

**Comment by kean** [comment]
The only holdout is not being able to use StateObject. I'm not sure there are any good ways to replicate it behavior.

**Comment by kylebrowning** [comment]
You can use ObservedObject and get most of it, im sure some things won't work, or be doable, but its better than none.

```swift

struct RemoteImageView: View {
    @ObservedObject var image: FetchImage

    let imageUrl: URL
    var contentMode: ContentMode = .fill

    public var body: some View {

        ZStack {
            image.view?
                .resizable()
                .aspectRatio(contentMode: contentMode)
        }
        .onAppear { image.load(imageUrl) }
        .onDisappear { image.reset() }
    }
}

@available(iOS 14, *)
struct RemoteRetainedImageView: View {
    @StateObject private var retainedImage = FetchImage()

    let imageUrl: URL
    var contentMode: ContentMode = .fill

    public var body: some View {

        ZStack {
            retainedImage.view?
                .resizable()
                .aspectRatio(contentMode: contentMode)
        }
        .onAppear { retainedImage.load(imageUrl) }
        .onDisappear { retainedImage.reset() }
    }
}

```

**Comment by kean** [comment]
I received multiple reports about issues when using `@ObservedObject` this way. Unless you make sure you retain the object (`FetchImage`) somewhere, you are going to run into problems.

**Comment by kylebrowning** [comment]
All good. We dropped support for 13
